### ISSUE TITLE
コロラド改が登録されない

### ISSUE THREAD

**Issue by kema8351** [ttdoda/MyFleetGirls#29]
コロラド改がMyFleetGirlsに登録されないようです。
ノーマルのページはありますが、改造先が出ていません。
https://myfleet.moe/entire/sta/book/601

多分、以下のコミットをリバートすれば解決すると思います。
https://github.com/ponkotuy/MyFleetGirls/commit/c1b4c1f82e970beec4043bd34e83cace4902154e#diff-e80aa14dfaecb3613b87fabc0fe77b70
コロラド改のIdが1496でShipIds.isSpecialShipIdに引っかかるのが原因だと思います。

**Comment by kema8351** [comment]
上記のコミットは、当時サラトガ改二が登録されないために入れた対策だったと思います。
https://github.com/ponkotuy/MyFleetGirls/issues/415

あのときからstart2のレスポンスが整理されて
問題になったid788～799のデータは送られてこなくなったようです。
1500以下を味方艦娘と見なす昔の方式に戻しても大丈夫だと思います。

**Comment by ttdoda** [comment]
ありがとうございます。
修正しました。
